backend:
  name: git-gateway
  branch: main # CAREFUL: when updating content in the CMS, it will update on the master branch

publish_mode: editorial_workflow
local_backend: true # allows for you to locally mess with your CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
editor:
  preview: false
collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "src/pages/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
  
  - name: "menu" # Used in routes, e.g., /admin/collections/blog
    label: "Menu" # Used in the UI
    folder: "src/pages/menu"
    create: false
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Voorgerecht", name: "voor", widget: "markdown"}
      - {label: "Hoofdgerecht", name: "hoofd", widget: "markdown"}
      - {label: "Nagerecht", name: "na", widget: "markdown"}