backend:
  name: git-gateway
  branch: main # CAREFUL: when updating content in the CMS, it will update on the master branch

publish_mode: editorial_workflow
local_backend: true # allows for you to locally mess with your CMS
media_folder: "public/images/uploads" # Media files will be stored in the repo under public/images/uploads
public_folder: "/images/uploads" # The src attribute for uploaded media will begin with /images/uploads
editor:
  preview: false
collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Home"
        name: "home"
        file: "src/pages/index.astro"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - {label: "Body", name: "body", widget: "markdown"}
      - label: "Over"
        name: "over"
        file: "src/pages/over.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Intro, name: intro, widget: markdown}
          - label: Over mij
            name: over
            widget: list
            fields:
              - {label: Full Name, name: name, widget: string}
              - {label: Position, name: position, widget: string}
              - {label: Photo, name: photo, widget: image}
              - {label: More, name: more, widget: markdown}
      - label: "Menu"
        name: "menu"
        file: "src/pages/menu.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
          - {label: "Voorgerecht", name: "voor", widget: "markdown"}
          - {label: "Hoofdgerecht", name: "hoofd", widget: "markdown"}
          - {label: "Nagerecht", name: "na", widget: "markdown"}